common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
                                                        #4: packet message comes from Protobuf-UDP
                                                        #5: point cloud comes from Protobuf-UDP
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
  send_packet_proto: false                              #true: Send packets through Protobuf-UDP
  send_point_cloud_proto: false                         #true: Send point cloud through Protobuf-UDP
  pcap_path: /home/robosense/lidar.pcap                 #The path of pcap file


lidar:   
# 10.1.100.9
  - driver:
      lidar_type: RS16            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_front           #Frame id of message
      msop_port: 9966              #Msop port of lidar
      difop_port: 8877             #Difop port of lidar
      start_angle: 270             #Start angle of point cloud
      end_angle: 180               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 150            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 3.14
      pitch: 0.0
      yaw: 0.0                                    
    ros:
      ros_recv_packet_topic: /front/rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /front/rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points/front_raw      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to      

      
# 10.1.100.10
  - driver:
      lidar_type: RS16            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_back       #Frame id of message
      msop_port: 6699              #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      start_angle: 270             #Start angle of point cloud
      end_angle: 180               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 150            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 3.14
      pitch: 0.0
      yaw: 3.14                                    
    ros:
      ros_recv_packet_topic: /back/rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /back/rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points/back_raw      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60024                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60024                     #Port number which the point cloud will be send to
      msop_recv_port: 60025                            #Port number used for receiving lidar msop packets
      msop_send_port: 60025                            #Port number which the msop packets will be send to 
      difop_recv_port: 60026                           #Port number used for receiving lidar difop packets
      difop_send_port: 60026                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to